In [1]:
from federated_learning.utils import SHAPUtil, VMUtil
from federated_learning import ClientPlane

In [2]:
%load_ext autoreload
%autoreload 2

# Configuration

In [3]:
import os
import torch.nn as nn
from torch import device
from federated_learning.nets import MNISTCNN, FashionMNISTCNN, MNISTFFNN
from federated_learning.dataset import MNISTDataset, FashionMNISTDataset
from federated_learning.client.ffnn_client import FFNNClient

In [4]:
class Configuration():
    
    # Dataset Config
    BATCH_SIZE_TRAIN = 132
    BATCH_SIZE_TEST = 1000
    DATASET = MNISTDataset
    
    #MNIST_FASHION_DATASET Configurations
    MNIST_FASHION_DATASET_PATH = os.path.join('./data/mnist_fashion')
    MNIST_FASHION_LABELS = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker',  'Bag', 'Ankle Boot']
    
    #MNIST_DATASET Configurations
    MNIST_DATASET_PATH = os.path.join('./data/mnist')
    
    #CIFAR_DATASET Configurations
    CIFAR10_DATASET_PATH = os.path.join('./data/cifar10')
    CIFAR10_LABELS = ['Plane', 'Car', 'Bird', 'Cat','Deer', 'Dog', 'Frog', 'Horse', 'Ship', 'Truck']
    
    #Model Training Configurations
    N_EPOCHS = 4
    LEARNING_RATE = 0.01
    MOMENTUM = 0.5
    LOG_INTERVAL = 10
    CRITERION = nn.CrossEntropyLoss
    NETWORK = MNISTFFNN
    NUMBER_TARGETS = 10
    
    #Local Environment Configurations
    NUMBER_OF_CLIENTS = 4
    CLIENT_TYPE = FFNNClient
    DEVICE = device('cpu')
    
    #Label Flipping Attack
    DATA_POISONING_PERCENTAGE = 1
    FROM_LABEL = 5
    TO_LABEL = 4
    
    #Victoria Metrics Configurations
    VM_URL = os.getenv('VM_URL') #URL settings in docker-compose.yml

# Monitoring

In [ ]:
class Observer():
    pass

In [ ]:
class ClientObserver():

In [5]:
config = Configuration()
vm = VMUtil(config)
data = config.DATASET(config)
shap_util = SHAPUtil(data.test_dataloader)
client_plane = ClientPlane(config, data, shap_util)

MNIST training data loaded.
MNIST test data loaded.
Create 4 clients


In [6]:
client_plane.clients[0].test()
for epoch in range(1, config.N_EPOCHS + 1):
    client_plane.clients[0].train(epoch)
    client_plane.clients[0].test()


Test set: Average loss: 0.0023, Accuracy: 1010/10000 (10%)

Train Epoch: 1 [0/15000 (0%)]	Loss: 2.305683
Train Epoch: 1 [13200/15000 (88%)]	Loss: 2.299002

Test set: Average loss: 0.0023, Accuracy: 1011/10000 (10%)

Train Epoch: 2 [0/15000 (0%)]	Loss: 2.280546
Train Epoch: 2 [13200/15000 (88%)]	Loss: 2.179739

Test set: Average loss: 0.0022, Accuracy: 3653/10000 (37%)

Train Epoch: 3 [0/15000 (0%)]	Loss: 2.068100
Train Epoch: 3 [13200/15000 (88%)]	Loss: 1.311837

Test set: Average loss: 0.0013, Accuracy: 7950/10000 (80%)

Train Epoch: 4 [0/15000 (0%)]	Loss: 1.288617
Train Epoch: 4 [13200/15000 (88%)]	Loss: 0.990910

Test set: Average loss: 0.0008, Accuracy: 8414/10000 (84%)



In [7]:
client_plane.clients[0].analize()

In [8]:
client_plane.clients[0].confusion_matrix.sum(1) #recall 1 for row

tensor([4900., 5675., 5160., 5050., 4910., 4460., 4790., 5140., 4870., 5045.])

In [9]:
client_plane.clients[0].confusion_matrix.sum(0) #precision 1 for collumn

tensor([ 4516.,  4855.,  2141., 22188.,  2204.,  1492.,  2316.,  6315.,  2268.,
         1705.])

In [ ]:
client_plane.clients[0].confusion_matrix

In [10]:
client_plane.clients[0].accuracy

0.8414

In [11]:
client_plane.clients[0].recall

tensor([0.5882, 0.5611, 0.3442, 0.7790, 0.3273, 0.2812, 0.4073, 0.5165, 0.3193,
        0.2458])

In [12]:
client_plane.clients[0].precision

tensor([0.6382, 0.6558, 0.8295, 0.1773, 0.7291, 0.8405, 0.8424, 0.4204, 0.6856,
        0.7273])

In [ ]:
print(client_plane.clients[0].shap_values[4][0])

# SHAP Metrics

In [ ]:
client_plane.clients[0].get_shap_values()
len(client_plane.clients[0].shap_values)

In [ ]:
client_plane.clients[0].plot_shap_values("./test.png")

In [ ]:
import numpy as np

In [ ]:
pos = np.sum(np.array(client_plane.clients[0].shap_values[4][0]) > 0)

In [ ]:
neg = np.sum(np.array(client_plane.clients[0].shap_values[4][0]) < 0)

In [ ]:
neu =np.sum(np.array(client_plane.clients[0].shap_values[4][0]) == 0)

In [ ]:
pos + neg + neu

In [ ]:
28*28 

In [ ]:
arr = client_plane.clients[0].shap_values[4][4]
arr[np.nonzero(arr)].mean()

In [ ]:
arr = client_plane.clients[0].shap_values[4][4]
arr.mean()

In [ ]:
def analize_shap():
    pass